### ISSUE TITLE
can't hide the fallback Web3 Wallet 

### ISSUE THREAD

**Issue by dkent600** [web3connect/web3connect#48] opened 2019-07-31 16:37 UTC
When there is no injected provider, Web3Connect used the "fallback" provider which is called "Web3", type "injected", check "isWeb3".

What is the point of this?  In what typical conditions will this fallback succeed?  Seems like it should not be displayed unless it has a chance to succeed.  For me, it is showing up and failing.  It is not even needed because I have Portis and Fortmatic showing (but not WalletConnect, and no extensions are available).

So to get rid of this, I tried supplying `disableInjectedProvider` and when I do, when the Modal comes up the fallback is not hidden (even though it is "injected"), and there is a console log message, even though I am passing `true`:

```
Warning: Failed prop type: The prop `injectedProvider` is marked as required in `Modal`, but its value is `null`.
    in Modal
checkPropTypes.js:20
```

How can I cause this fallback to not be shown?  Thanks.

**Comment by crisgarner** [comment] 2019-07-31 17:07
The idea of the fallback is for injected providers that haven't been added to the library or that don't support the normal specification. Opera is an example of it.

The problem that you have is that you don't want the injected provider to appear and when you supply disableInjectedProvider it is shown?

**Comment by dkent600** [comment] 2019-07-31 18:15
> The problem that you have is that you don't want the injected provider to appear and when you supply disableInjectedProvider it is shown?

I would prefer that the fallback button not appear if it is only going to fail if the user selects it.  If that is not possible, then I'd like to be able to hide it by setting `disableInjectedProvider`, say, when I can't find `window.web3` or `window.ethereum` (anticipating on my own that it is going to fail).

**Comment by crisgarner** [comment] 2019-07-31 18:59
There was a bug that didn't hide the injected provider using disableInjectedProvider

**Comment by dkent600** [comment] 2019-08-02 15:23
Cool, but best would still be if the Web3 button were not be displayed if there is no injected extension to work with.  In that case it is worse than worthless, as it crashes.

What is the dApp expected to do in this situation?  I'm not sure that expecting the dApp to know whether to disable extensions (even if that works now) is a friendly UX.  (`disableInjectedProvider: !((window as any).web3 || (window as any).ethereum)`) Would be better IMHO that Web3Connect be smarter on its own about when to show the fallback.

**Comment by crisgarner** [comment] 2019-08-02 16:31
I'll open it again and check it out since what you describe should be the default functionality and shouldn't crash.

**Comment by crisgarner** [comment] 2019-08-02 16:32
The problem is: "If you have no web3 injected provider it crashes"? right? @dkent600

**Comment by dkent600** [comment] 2019-08-02 17:36
@crisgarner  

> If you have no web3 injected provider it crashes

Yes, last i checked.

**Comment by crisgarner** [comment] 2019-08-02 18:03
![Screenshot from 2019-08-02 11-59-22](https://user-images.githubusercontent.com/578688/62389623-89145180-b51d-11e9-96c4-7f084df3fc24.png)
I think, this was fixed on the 1.0.0 release

**Closed by crisgarner** 2019-08-02 18:03 UTC
Labels: bug

**Comment by dkent600** [comment] 2019-08-03 02:10
@crisgarner So now I'm curious, when is the fallback provider supposed to be displayed?  I'm having trouble now making it appear. Thanks.

**Comment by dkent600** [comment] 2019-08-03 03:03
Oh, with Opera, I see it, thanks
